# Generated by Django 4.1.3 on 2023-04-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_customuser_car_purchaseparticipation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='car',
        ),
        migrations.DeleteModel(
            name='PurchaseParticipation',
        ),
    ]
