# Generated by Django 4.1.3 on 2023-05-03 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostItShowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showed', to='postit.postit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
