# Generated by Django 4.1.3 on 2023-05-19 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_reservation_confirmations'),
        ('postit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='cars.reservation'),
        ),
    ]
