# Generated by Django 4.1.3 on 2023-05-03 10:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postit', '0002_postitshowed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostItShowed',
            new_name='PostItNotShowed',
        ),
    ]
