# Generated by Django 4.1.3 on 2023-05-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_insurance_car'),
        ('postit', '0003_rename_postitshowed_postitnotshowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='postit',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='cars.reservation'),
        ),
    ]
