# Generated by Django 4.1.3 on 2023-04-25 09:10

import cars.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('immatriculation', models.CharField(blank=True, max_length=100, null=True)),
                ('energy', models.CharField(choices=[('essence', "Fonctionne à l'essence"), ('diesel', 'Fonctionne au diesel'), ('électricité', 'Véhicule électrique'), ('hybride non rechargeable', 'Véhicule hybride non rechargeable'), ('hybride rechargeable', 'Véhicule hybride rechargeable'), ('gpl', 'Fonctionne au GPL')], default='essence', max_length=32)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to=cars.models.path_and_rename)),
                ('price', models.FloatField(blank=True, max_length=100, null=True)),
                ('insurance_renewal', models.DateTimeField(blank=True, null=True)),
                ('creation_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
