# Generated by Django 4.1.3 on 2023-05-12 13:55

import cars.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nb_users', models.IntegerField(default=2)),
                ('immatriculation', models.CharField(blank=True, max_length=100, null=True)),
                ('energy', models.CharField(choices=[('essence', "Fonctionne à l'essence"), ('diesel', 'Fonctionne au diesel'), ('électricité', 'Véhicule électrique'), ('hybride non rechargeable', 'Véhicule hybride non rechargeable'), ('hybride rechargeable', 'Véhicule hybride rechargeable'), ('gpl', 'Fonctionne au GPL')], default='essence', max_length=32)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to=cars.models.path_and_rename)),
                ('price', models.FloatField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(default=None, max_length=255, null=True, unique=True)),
                ('creation_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, max_length=100)),
                ('quantity', models.FloatField(default=0, max_length=100)),
                ('paid_day', models.DateField()),
                ('type_energy', models.CharField(choices=[('essence', 'essence'), ('diesel', 'diesel'), ('électricité', 'kwatt'), ('gpl', 'GPL')], default='essence', max_length=32)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to=cars.models.path_and_rename_bill)),
                ('slug', models.SlugField(default=None, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=100)),
                ('renewal_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.FloatField(max_length=100)),
                ('first_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('paid_day', models.DateField()),
                ('type_repair', models.CharField(choices=[('entretien', 'entretien'), ('importante', 'réparation importante')], default='entretien', max_length=32)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to=cars.models.path_and_rename_bill)),
                ('slug', models.SlugField(default=None, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('demand_date', models.DateField(auto_now_add=True)),
                ('reservation_start', models.DateTimeField()),
                ('reservation_end', models.DateTimeField()),
                ('reservation_end_calendar', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Cancelled by owner'), ('cancelled', 'Cancelled by requester'), ('on_going', 'Product actually borrowed by requester '), ('returned', 'Product returned by the borrower')], default='pending', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_km_start', models.IntegerField(default=0)),
                ('nb_km_end', models.IntegerField(default=0)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='cars.car')),
            ],
        ),
    ]
