# Generated by Django 4.1.3 on 2023-04-26 10:33

import cars.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('immatriculation', models.CharField(blank=True, max_length=100, null=True)),
                ('energy', models.CharField(choices=[('essence', "Fonctionne à l'essence"), ('diesel', 'Fonctionne au diesel'), ('électricité', 'Véhicule électrique'), ('hybride non rechargeable', 'Véhicule hybride non rechargeable'), ('hybride rechargeable', 'Véhicule hybride rechargeable'), ('gpl', 'Fonctionne au GPL')], default='essence', max_length=32)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to=cars.models.path_and_rename)),
                ('price', models.FloatField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(default=None, max_length=255, null=True, unique=True)),
                ('creation_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=100)),
                ('renewal_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_km_start', models.IntegerField()),
                ('nb_km_end', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='cars.car')),
            ],
        ),
    ]
