# Generated by Django 4.1.3 on 2023-05-12 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_trip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='cars.car'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reservation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repair',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_bill', to='cars.car'),
        ),
        migrations.AddField(
            model_name='repair',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_repair_bill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseparticipation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_participation', to='cars.car'),
        ),
        migrations.AddField(
            model_name='purchaseparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceparticipation',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_participation', to='cars.insurance'),
        ),
        migrations.AddField(
            model_name='insuranceparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_insurance_participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurance',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='cars.car'),
        ),
        migrations.AddField(
            model_name='energy',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_bill', to='cars.car'),
        ),
        migrations.AddField(
            model_name='energy',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_energy_bill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='users',
            field=models.ManyToManyField(related_name='car_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
