# Generated by Django 4.1.3 on 2023-05-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseparticipation',
            name='first_complete',
            field=models.BooleanField(default=False),
        ),
    ]
