# Generated by Django 4.1.3 on 2023-05-09 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_insurance_participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
