# Generated by Django 4.1.3 on 2023-04-25 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_car_users_purchaseparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='insurance_renewal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='users',
            field=models.ManyToManyField(related_name='car_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
