# Generated by Django 4.1.3 on 2023-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='nb_km_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='nb_km_start',
            field=models.IntegerField(default=0),
        ),
    ]
