# Generated by Django 4.1.3 on 2023-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_insuranceparticipation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceparticipation',
            name='first_complete',
            field=models.BooleanField(default=False),
        ),
    ]
