# Generated by Django 4.1.3 on 2023-04-25 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_car_slug_alter_car_insurance_renewal_alter_car_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='insurance_renewal',
        ),
        migrations.AlterField(
            model_name='purchaseparticipation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_participation', to='cars.car'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=100)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='cars.car')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
