# Generated by Django 4.1.3 on 2023-05-16 08:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0004_alter_energy_type_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_energy_bill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='energy',
            name='paid_day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
