# Generated by Django 4.1.3 on 2023-04-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='price',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
