# Generated by Django 4.1.3 on 2023-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_energy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='type',
        ),
        migrations.AddField(
            model_name='energy',
            name='quantity',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='energy',
            name='type_energy',
            field=models.CharField(choices=[('essence', 'essence'), ('diesel', 'diesel'), ('électricité', 'kwatt'), ('gpl', 'GPL')], default='essence', max_length=32),
        ),
    ]
