# Generated by Django 4.1.3 on 2023-05-19 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_energy_paid_by_alter_energy_paid_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmations',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='energy',
            name='paid_day',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
