# Generated by Django 4.1.3 on 2023-05-19 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0006_reservation_confirmations_alter_energy_paid_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='confirmations',
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmations',
            field=models.ManyToManyField(blank=True, null=True, related_name='confirmations', to=settings.AUTH_USER_MODEL),
        ),
    ]
