# Generated by Django 4.1.3 on 2023-05-19 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0007_remove_reservation_confirmations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmations',
            field=models.ManyToManyField(blank=True, related_name='confirmations', to=settings.AUTH_USER_MODEL),
        ),
    ]
