# Generated by Django 4.1.3 on 2023-05-19 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0008_alter_reservation_confirmations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmations',
            field=models.ManyToManyField(blank=True, related_name='confirmed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
