# Generated by Django 4.1.3 on 2023-05-03 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0009_alter_repair_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
