# Generated by Django 4.1.3 on 2023-05-03 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end',
            new_name='reservation_end',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start',
            new_name='reservation_start',
        ),
        migrations.AddField(
            model_name='reservation',
            name='demand_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting for confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Cancelled by owner'), ('cancelled', 'Cancelled by requester'), ('on_going', 'Product actually borrowed by requester '), ('returned', 'Product returned by the borrower')], default='pending', max_length=32),
        ),
    ]
