# Generated by Django 4.1.3 on 2023-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_rename_end_reservation_reservation_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='nb_users',
            field=models.IntegerField(default=2),
        ),
    ]
