# Generated by Django 4.1.3 on 2023-05-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_car_nb_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='cars.car'),
        ),
    ]
