# Generated by Django 4.1.3 on 2023-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_insurance_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_end_calendar',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
